name: "Nightly CI"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-6'

jobs:
  nightly-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(lockfile): update flake.lock"
          commit-msg: "chore(lockfile): update flake.lock"
          token: ${{ secrets.GH_TOKEN }}
          pr-labels: |
            dependencies
            automated
            nightly
      - if: steps.update.outputs.pull-request-number
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
