name: Nightly update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  nightly-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "holster"
      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            lazy-trees = true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - id: update
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-msg: "chore(lockfile): update flake.lock"
          pr-title: "chore(lockfile): update flake.lock"
          pr-labels: |
            dependencies
            automated
            nightly
      - if: steps.update.outputs.pull-request-number
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
